# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VDB
  pod 'RealmSwift'

  target 'VDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VDBUITests' do
    # Pods for testing
  end

end
